### ISSUE TITLE
這學期會有testcase嗎

### ISSUE THREAD

**Issue by NaoCoding** [Darrin-Lin/2023_NTNU_ComputerProgramming-I_TestCase#3]
如題，德恩要繼續做功德嗎 XD。
還是這學期就看看題目，有些題目比較不方便就算ㄌ

**Comment by Darrin-Lin** [comment]
程設二的在這，之後會更新，如果有人的測資也要丟在我這，我再看看怎麼處理
https://github.com/Darrin-Lin/2024_NTNU_ComputerProgramming-II_TestCase
